Tasker/Controllers/ObjectiveController.cs
using System.Web.Mvc;
using BusinessLogic;
using Domain;


namespace Tasker.Controllers
{
    public class ObjectiveController : Controller
    {
        ObjectiveManager _objectiveManager = new ObjectiveManager();

        public ActionResult Index()
        {
            return View(_objectiveManager.GetAll());
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View(new Objective());
        }

        [HttpPost]
        public ActionResult Add(Objective objective)
        {
            if (!ModelState.IsValid)
            {
                return View(objective);
            }

            _objectiveManager.Add(objective);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Objective editingObjective = _objectiveManager.Find(id);

            return View(editingObjective);
        }

        [HttpPost]
        public ActionResult Edit(Objective editedObjective)
        {
            _objectiveManager.Edit(editedObjective);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            _objectiveManager.Delete(id);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _objectiveManager.Dispose();
            base.Dispose(disposing);
        }
    }
}

Tasker/Views/Objective/Add.cshtml
@model Domain.Objective

@{
    ViewBag.Title = "Добавление задачи";

    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Добавление задачи</h2>
@using (Html.BeginForm("Add", "Objective"))
{
    @Html.HiddenFor(record => record.Id)

    <div class="form-group">

        @Html.LabelFor(record => record.Name)
        @Html.TextBoxFor(record => record.Name, new {@class = "form-control", placeholder = "Mаксимально 200 символов!"})

    </div>

    <input type="submit" class="btn btn-success" value="Отправить"/>
}

Tasker/Views/Objective/Edit.cshtml
@model Domain.Objective

@{
    ViewBag.Title = "Редактировать задачу";

    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Редактировать задачу</h2>

@using (Html.BeginForm("Edit", "Objective"))
{
    @Html.HiddenFor(record => record.Id)


    <div class="form-group">
        <p>Mаксимально 200 символов!</p>
        @Html.LabelFor(record => record.Name)
        @Html.TextBoxFor(record => record.Name, new {@class = "form-control"})
    </div>

    <div class="form-group">
        @Html.CheckBoxFor(record => record.Completed)
        @Html.LabelFor(record => record.Completed, new {@class = "form-check-label"})
    </div>


    <div class="form-group">
        <input type="submit" class="btn btn-success" value="Отправить"/>
    </div>
}

Tasker/Views/Objective/Index.cshtml
@model IEnumerable<Domain.Objective>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="card-container">
        @foreach (var objective in Model)
        {
            <div class="card col-md-4">
                <div class="card-body">
                    <h5>@objective.Name</h5>

                    <p>Создано: @objective.StarDate.ToLocalTime()</p>

                    <div class="form-check disabled">
                        <label class="form-check-label">
                            @Html.CheckBoxFor(record => objective.Completed, new {disabled = true})
                            @if (objective.Completed)
                            {
                                <span>Выполнено</span>
                            }
                            else
                            {
                                <span>Не выполнено</span>
                            }
                        </label>
                    </div>
                    @Html.ActionLink("Редактировать", "Edit", "Objective", new {id = @objective.Id}, new {@class = "card-link btn btn-success"})

                    @Html.ActionLink("Удалить", "Delete", "Objective", new {id = @objective.Id}, new {@class = "card-link btn btn-danger"})
                </div>
            </div>
        }
    </div>
</div>

Tasker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Tasker</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Задачи", "Index", "Objective", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Добавить", "Add", "Objective")</li>
            </ul>
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Tasker</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>